# Generated by Django 5.0.2 on 2024-12-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dimba', '0003_alter_group_options_remove_group_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
