# Generated by Django 5.0.2 on 2024-12-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dimba', '0004_turf_opening_hours_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='group',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('pro', 'Pro')], default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, default='default_group.jpg', null=True, upload_to='group_images/'),
        ),
    ]
