# Generated by Django 5.0.2 on 2024-12-13 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dimba', '0006_remove_group_level_remove_group_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='image',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
    ]
