# Generated by Django 5.0.2 on 2024-12-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dimba', '0007_remove_group_image_remove_group_members'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='dimba_group',
        ),
    ]
