# Generated by Django 5.0.2 on 2024-12-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dimba', '0008_alter_group_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images/'),
        ),
        migrations.AddField(
            model_name='group',
            name='skill_level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
    ]
