# Generated by Django 5.0.2 on 2024-12-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dimba', '0009_group_image_group_skill_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
